### ISSUE TITLE
Как кастомизировать данное решение

### ISSUE THREAD

**Issue by maxyc** [DevGroup-ru/yii2-dropzone#4]
Прошу прощения, возможно, за глупый вопрос.
А как кастомизировать? Как мне убрать эту картинку с перетаскиванием и свои стили применить? Перекрывать css? может есть возможность о которой я не догадываюсь?

**Comment by evgen-d** [comment]
Данное расширение всего лишь использует js плагин и оформляет его в качестве виджета yii2

Могу предложить пару решений:
- унаследовать класс с ассетами и задать там свой css
- прописать кастомный css в конфигурационном файле в директиве assetManager

**Comment by maxyc** [comment]
спасибо. с этой целью и спрашивал. подтвердить свои догадки ) мало ли, мож в yii чего не знаю
