### ISSUE TITLE
Ошибка в $storedFiles

### ISSUE THREAD

**Issue by shastox** [DevGroup-ru/yii2-dropzone#8]
Не получается отобразить несколько файлов, сохраненных ранее на сервере, используя storedFiles. Отображается только один файл.

Причина:
https://github.com/DevGroup-ru/yii2-dropzone/blob/master/DropZone.php#L52 вот этот js-код регистрируется только один раз (т.к строка не зависит от переменной $file  и поэтому генерируется одинаковый $key  в методе registerJs). А нужно, чтобы строка эта генерировалась для каждого файла.

**Comment by fps01** [comment]
Thanks for bug report!
